### ISSUE TITLE
feat: rework remote IP detection

### ISSUE THREAD

**Issue by fty4** [taskmedia/ddns-allowlist#21]
Currently all different IP sources are used:

- `X-Forwarded-For`
- `RemoteAddr`
- `Cf-Connecting-Ip`
- ~~`X-Real-Ip`~~

For security reasons this might be reworked.

The `Cf-Connecting-Ip` might be added manually and access can be granted.
```bash
$ curl https://my.site/ -H "Cf-Connecting-Ip: 1.2.3.4"
...
RemoteAddr: 1.1.1.1:9999
...
Cf-Connecting-Ip: 1.2.3.4
X-Forwarded-For: 2.2.2.2
...
X-Real-Ip: 2.2.2.2
```

Maybe Cloudflare should be an option that can be enabled in the config e.g.:
```yaml
ddns-whitelist-router:
  plugin:
    ddns-whitelist:
      cloudflare: true
      hostList:
        - my.router.ddns.tld
```

or the user can specify where the IP will be fetched from (maybe also with a priority list?)

related to #17
